stages:
  - build

build:php-7.1-amd64:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE: jostdevops/symfony-app:php7.1-amd64
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - docker build -t ${IMAGE} php-7.1/
    - docker push ${IMAGE}

build:php-7.1-arm64:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE: jostdevops/symfony-app:php7.1-arm64
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - docker build -t ${IMAGE} php-7.1/
    - docker push ${IMAGE}
  tags:
    - arm64
