language: bash
services: docker

env:
  - VERSION=php-7.0
  - VERSION=php-7.1
  - VERSION=php-7.2

before_script:
  - env | sort
  - cd "dnl-jst/symfony-app/$VERSION"

script:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "dnljst/symfony-app:$VERSION" .
    ) 
#  - docker push dnljst/symfony-app:$VERSION
